


SELECT * FROM 
CUSTOMERS JOIN ORDERS ON CUSTOMERS.CUSTOMERID = ORDERS.CUSTOMERID
WHERE CUSTOMERS.COUNTRY = 'USA'
AND CUSTOMERS.CUSTOMERID LIKE 'LA%'
AND EMPLOYEEID IN 
(SELECT EMPLOYEEID FROM ORDERS WHERE SHIPCOUNTRY = 'SWITZERLAND')


