SELECT CUSTOMERS.CUSTOMERID, EMPLOYEEID, City, PRODUCTS.ProductID, PRODUCTS.UnitsInStock, 
	   ORDERDETAILS.DISCOUNT
FROM CUSTOMERS, ORDERS, ORDERDETAILS, PRODUCTS
WHERE CUSTOMERS.CUSTOMERID = ORDERS.CUSTOMERID AND
	 ORDERS.OrderID = ORDERDETAILS.OrderID AND
	  ORDERDETAILS.ProductID = PRODUCTS.ProductID AND
	  EmployeeID = 1 AND
	  City = 'London' AND
	  ORDERDETAILS.Discount = 0 AND
	  PRODUCTS.UnitsInStock < 20

	  