SET ANSI_PADDING ON

CREATE NONCLUSTERED INDEX [_dta_index_Customers_6_2026542353__K6_K1] ON [dbo].[Customers]
(
	[City] ASC,
	[CustomerID] ASC
)WITH (SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF) ON [PRIMARY];
GO
CREATE NONCLUSTERED INDEX [_dta_index_OrderDetails_6_2058542467__K1_K5_K2] ON [dbo].[OrderDetails]
(
	[OrderID] ASC,
	[Discount] ASC,
	[ProductID] ASC
)WITH (SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF) ON [PRIMARY]
GO
SET ANSI_PADDING ON

CREATE NONCLUSTERED INDEX [_dta_index_Orders_6_2042542410__K3_K2_K1] ON [dbo].[Orders]
(
	[EmployeeID] ASC,
	[CustomerID] ASC,
	[OrderID] ASC
)WITH (SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [_dta_index_Products_6_2074542524__K7_K1] ON [dbo].[Products]
(
	[UnitsInStock] ASC,
	[ProductID] ASC
)WITH (SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF) ON [PRIMARY]



DROP INDEX CUSTOMERS.[_dta_index_Customers_6_2026542353__K6_K1];
DROP INDEX ORDERS.[_dta_index_Orders_6_2042542410__K3_K2_K1];
DROP INDEX ORDERDETAILS.[_dta_index_OrderDetails_6_2058542467__K1_K5_K2];
DROP INDEX PRODUCTS.[_dta_index_Products_6_2074542524__K7_K1]